name: alef_parents
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_i18n: ^0.34.0
  equatable: ^2.0.5
  multiselect: ^0.1.0
  geolocator: ^10.1.0
  multi_select_flutter: ^4.1.3
  permission_handler: ^11.0.1
  app_settings: ^5.1.1
  getwidget: ^4.0.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^2.1.1
  location: ^5.0.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  ff_bloc: ^1.0.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  image: ^4.1.3
  photo_view: ^0.14.0
  url_launcher: ^6.2.1
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  google_polyline_algorithm: ^3.1.0
  cached_network_image: ^3.3.0
  draggable_bottom_sheet: ^1.0.2
  table_calendar: ^3.0.9
  file_picker: ^6.1.1
  dio: ^5.4.0
  path: ^1.8.3
  dotted_border: ^2.1.0
  mime_type: ^1.0.0
  image_picker: ^1.0.4
  async: ^2.11.0
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  google_sign_in: ^6.1.6
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.1.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  pay: ^1.1.2
  flutter_stripe: ^9.5.0+1
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  lottie: ^2.7.0
  share: ^2.0.4
  path_provider: ^2.1.1
  pdf: ^3.10.7
  number_display: ^3.0.0
  screenshot: ^2.1.0
  mailer: ^6.0.1
  device_calendar: ^4.3.2
#  add_2_calendar: ^3.0.1 //TODO downgrade
  flutter_pdfview: ^1.3.2
  firebase_installations: ^16.3.6
  add_2_calendar: ^2.2.5
  pie_chart: ^5.4.0
  # dcdg: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

flutter_intl:
  enabled: true
